SUNDIALS_DIR := /home/qianruw/2025summer/sundials-install
INCLUDE_FLAGS := -I$(SUNDIALS_DIR)/include
LIBRARY_FLAGS := -L$(SUNDIALS_DIR)/lib64
LDLIBS := -lsundials_cvode -lsundials_nvecserial -lsundials_sunmatrixdense -lsundials_sunlinsoldense -lsundials_core -lm

CC := gcc
TARGET := ode1
SRC := ode1.c

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(INCLUDE_FLAGS) -o $@ $< $(LIBRARY_FLAGS) $(LDLIBS)

run: $(TARGET)
	LD_LIBRARY_PATH=$(SUNDIALS_DIR)/lib64 ./$(TARGET)

clean:
	rm -f $(TARGET)
